apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: horamind

resources:
  - namespace.yaml
  - config.yaml
  - postgres.yaml
  - chroma.yaml
  - api.yaml
  - edge.yaml

commonLabels:
  app.kubernetes.io/part-of: horamind

images:
  - name: ghcr.io/harieshwar-j-a/horamind-api
    newTag: latest
