import type { Sql } from '../db/client.js';
import type { AuthProvider } from '@horamind/shared';
import type { Tier } from '@horamind/shared';

/**
 * User and identity persistence.
 *
 * SQL is written here rather than generated by an ORM. The migrations already
 * use plpgsql triggers, partial unique indexes and functions that a schema DSL
 * cannot express, so SQL is the source of truth either way; adding a second
 * definition of the same tables would only give it something to drift from.
 */

export interface UserRow {
    id: string;
    publicId: string;
    email: string;
    emailVerifiedAt: Date | null;
    passwordHash: string | null;
    displayName: string | null;
    tier: Tier;
    locale: string;
    timezone: string;
    adsEnabled: boolean;
    createdAt: Date;
    deletedAt: Date | null;
}

export async function findUserById(sql: Sql, id: string): Promise<UserRow | null> {
    const [row] = await sql<UserRow[]>`
        SELECT id, public_id, email, email_verified_at, password_hash, display_name,
               tier, locale, timezone, ads_enabled, created_at, deleted_at
          FROM users
         WHERE id = ${id} AND deleted_at IS NULL`;
    return row ?? null;
}

export async function findUserByEmail(sql: Sql, email: string): Promise<UserRow | null> {
    const [row] = await sql<UserRow[]>`
        SELECT id, public_id, email, email_verified_at, password_hash, display_name,
               tier, locale, timezone, ads_enabled, created_at, deleted_at
          FROM users
         WHERE lower(email) = lower(${email}) AND deleted_at IS NULL`;
    return row ?? null;
}

/**
 * Create a user and their first identity in one transaction.
 *
 * Atomicity matters: a user row without an identity is an account nobody can
 * sign into, and it would occupy the email address permanently.
 */
export async function createUserWithIdentity(
    sql: Sql,
    input: {
        email: string;
        passwordHash: string | null;
        displayName: string | null;
        timezone: string;
        emailVerified: boolean;
        provider: AuthProvider;
        providerAccountId: string;
    },
): Promise<UserRow> {
    return sql.begin(async tx => {
        const [user] = await tx<UserRow[]>`
            INSERT INTO users (public_id, email, password_hash, display_name, timezone, email_verified_at)
            VALUES (allocate_public_id(), ${input.email}, ${input.passwordHash},
                    ${input.displayName}, ${input.timezone},
                    ${input.emailVerified ? sql`now()` : null})
            RETURNING id, public_id, email, email_verified_at, password_hash, display_name,
                      tier, locale, timezone, ads_enabled, created_at, deleted_at`;

        if (!user) throw new Error('User insert returned no row');

        await tx`
            INSERT INTO identities (user_id, provider, provider_account_id, email_at_provider)
            VALUES (${user.id}, ${input.provider}, ${input.providerAccountId}, ${input.email})`;

        return user;
    }) as Promise<UserRow>;
}

export async function findUserByProviderAccount(
    sql: Sql,
    provider: AuthProvider,
    providerAccountId: string,
): Promise<UserRow | null> {
    const [row] = await sql<UserRow[]>`
        SELECT u.id, u.public_id, u.email, u.email_verified_at, u.password_hash, u.display_name,
               u.tier, u.locale, u.timezone, u.ads_enabled, u.created_at, u.deleted_at
          FROM identities i
          JOIN users u ON u.id = i.user_id
         WHERE i.provider = ${provider}
           AND i.provider_account_id = ${providerAccountId}
           AND u.deleted_at IS NULL`;
    return row ?? null;
}

export async function linkIdentity(
    sql: Sql,
    userId: string,
    provider: AuthProvider,
    providerAccountId: string,
    emailAtProvider: string | null,
): Promise<void> {
    await sql`
        INSERT INTO identities (user_id, provider, provider_account_id, email_at_provider)
        VALUES (${userId}, ${provider}, ${providerAccountId}, ${emailAtProvider})
        ON CONFLICT (provider, provider_account_id) DO NOTHING`;
}

export async function listLinkedProviders(sql: Sql, userId: string): Promise<AuthProvider[]> {
    const rows = await sql<{ provider: AuthProvider }[]>`
        SELECT provider FROM identities WHERE user_id = ${userId} ORDER BY created_at`;
    return rows.map(r => r.provider);
}

export async function touchIdentityUse(
    sql: Sql,
    provider: AuthProvider,
    providerAccountId: string,
): Promise<void> {
    await sql`
        UPDATE identities SET last_used_at = now()
         WHERE provider = ${provider} AND provider_account_id = ${providerAccountId}`;
}

export async function setPasswordHash(sql: Sql, userId: string, hash: string): Promise<void> {
    await sql`
        UPDATE users SET password_hash = ${hash}, updated_at = now()
         WHERE id = ${userId}`;
}

export async function markEmailVerified(sql: Sql, userId: string): Promise<void> {
    await sql`
        UPDATE users SET email_verified_at = now(), updated_at = now()
         WHERE id = ${userId} AND email_verified_at IS NULL`;
}

/**
 * Begin account deletion.
 *
 * Soft first: `purge_deleted_users()` finishes the job after the grace period.
 * Every session is revoked immediately, because a deletion request must log the
 * user out everywhere even though their data survives for another 30 days.
 */
export async function softDeleteUser(sql: Sql, userId: string): Promise<void> {
    await sql.begin(async tx => {
        await tx`UPDATE users SET deleted_at = now() WHERE id = ${userId}`;
        await tx`UPDATE sessions SET revoked_at = now()
                  WHERE user_id = ${userId} AND revoked_at IS NULL`;
    });
}
